services:
  redis:
    container_name: redis
    image: redis:7.2.4-alpine

  django:
    container_name: django
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: ./backend
    command: celery -A core.celery worker --loglevel=INFO
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - django
  
  celery2:
    container_name: celery2
    build:
      context: ./celeryworker
    command: celery -A celerytask worker --loglevel=INFO
    volumes:
      - ./celeryworker:/app
    depends_on:
      - redis    
      - django


